<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>
<?php require("templates/loginModal.phtml"); ?>
<?php require("templates/editUserModal.phtml"); ?>
<?php require("templates/editTeamModal.phtml"); ?>
<?php require("templates/deleteUserWarning.phtml"); ?>
<?php require("templates/deleteTeamWarning.phtml"); ?>

    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                        <?php if (isset($_SESSION['isAdmin'])) : ?>

                        <h1>Welcome, <?php echo $_SESSION['username'] ?>!</h1>

                        <!-- NAVIGATION FOR ADMIN -->
                        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Create User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Create Team</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="pills-contact3-tab" data-toggle="pill" href="#pills-contact3" role="tab" aria-controls="pills-contact3" aria-selected="false">View All Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="pills-contact4-tab" data-toggle="pill" href="#pills-contact4" role="tab" aria-controls="pills-contact4" aria-selected="false">View All Teams</a>
                            </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="pills-contact5-tab" data-toggle="pill" href="#pills-contact5" role="tab" aria-controls="pills-contact5" aria-selected="false">View Logs</a>
                                </li>

                        </ul>
                        <div class="tab-content" id="pills-tabContent">
                            <!-- CREATE A USER -->
                            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                                <span id="createUserError"></span>
                                <form method="post" id="createUserForm">
                                    <div class="form-row">
                                        <div class="col">
                                            <label for="firstName">First Name: </label>
                                            <input type="text" name="firstName" id="firstName" class="form-control" placeholder="Joe" required>
                                        </div>
                                        <div class="col">
                                            <label for="lastName">Last Name: </label>
                                            <input type="text" name="lastName" id="lastName" class="form-control" placeholder="Bloggs" required>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col">
                                            <label for="email">Email: </label>
                                            <input type="text" name="username" id="email" class="form-control" placeholder="john.doe@example.com" required>
                                        </div>
                                        <div class="col">
                                            <label for="password">Password: </label>
                                            <input type="password" name="password" id="password" placeholder="Password" class="form-control" required>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Team: </label>
                                        <select class="form-control" name="teamID">
                                            <?php
                                            foreach ($view->teams as $team) {
                                                ?>
                                                <option value="<?php echo $team->getTeamID() ?>">
                                                    <?php echo $team->getTeamName() ?>
                                                </option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" name="isAdmin" id="isadmin">
                                        <label class="form-check-label" for="isadmin">Admin?</label>
                                    </div>
                                    <br>
                                    <button type="submit" name="submit" class="btn btn-primary">Create</button>
                                </form>

                            </div>

                            <!-- CREATE A TEAM -->
                            <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
                                <span id="createTeamError"></span>
                                <form method="post" id="createTeamForm">
                                    <div class="form-group">
                                        <label for="teamname">Team Name: </label>
                                        <input type="text" name="teamName" id="teamname" placeholder="Enter a Team Name" class="form-control">
                                    </div>
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" name="isBusy" id="isBusy">
                                        <label class="form-check-label" for="isBusy">Busy?</label>
                                    </div>
                                    <br>
                                    <button type="submit" name="submit" class="btn btn-primary">Create</button>
                                </form>

                            </div>

                            <!-- VIEW ALL USERS -->
                            <div class="tab-pane fade" id="pills-contact3" role="tabpanel" aria-labelledby="pills-contact-tab">
                                <div class="row" id="userSearch">
                                    <div class="col-md-12 mx-auto">
                                        <form action="adminPanel.php" method="POST">
                                            <div class="form-group">
                                                <label class="col-form-label" for="name">First Name</label>
                                                <input class="form-control" type="text" placeholder="Jon Snow" name="name">
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" class="btn btn-primary" name="nameSubmit" value="Search Users">
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="row" id="users">
                                    <div class="col-md-12 mx-auto">
                                        <div class="card card-body bg-light mt-5">
                                            <h1 class="card-title">Users</h1>

                                            <div class="table-overflow-y table-scroll">
                                            <table class="table table-bordered table-striped mb-0">
                                                <tr>
                                                    <th>Username</th>
                                                    <th>FirstName</th>
                                                    <th>Last Name</th>
                                                    <th>Team</th>
                                                    <th>Admin</th>
                                                    <th></th>
                                                    <th></th>
                                                </tr>
                                                <?php
                                                foreach ($view->users as $user){
                                                    ?>
                                                    <tr>
                                                        <td><?php echo $user->getUsername() ?></td>
                                                        <td><?php echo $user->getFirstname() ?></td>
                                                        <td><?php echo $user->getLastname() ?></td>
                                                        <td><?php echo $user->getTeamName() ?></td>
                                                        <td><?php echo $user->getIsAdmin() ?></td>
                                                        <td>
                                                            <button type="button" class="btn btn-warning editUserBtn" data-id="<?php echo $user->getUserID() ?>" data-toggle="modal" data-target="#editUserModal">
                                                                Edit
                                                            </button>
                                                        </td>
                                                        <td>
                                                            <button type="button" class="btn btn-danger deleteUserBtn" data-id="<?php echo $user->getUserID() ?>" data-toggle="modal" data-target="#deleteUserWarning">
                                                                Delete
                                                            </button>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                ?>
                                            </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <!-- VIEW ALL TEAMS OPTION TO EDIT AND DELETE -->
                            <div class="tab-pane fade" id="pills-contact4" role="tabpanel" aria-labelledby="pills-contact-tab">
                                
                                <div class="row" id="teamsSearch">
                                    <div class="col-md-12 mx-auto">
                                        <form action="adminPanel.php" method="POST">
                                            <div class="form-group">
                                                <label class="col-form-label" for="name">Team Name</label>
                                                <input class="form-control" type="text" placeholder="Team Stark" name="name">
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" class="btn btn-primary" name="teamSubmit" value="Search Users">
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="row" id="teams">
                                    <div class="col-md-10 mx-auto">
                                        <div class="card card-body bg-light mt-5">
                                            <h1 class="card-title">Teams</h1>

                                            <div class="table-overflow-y table-scroll">
                                            <table class="table">
                                                <tr>
                                                    <th>Team Name</th>
                                                    <th>Is Busy</th>
                                                    <th>Edit</th>
                                                    <th>Delete</th>
                                                </tr>
                                                <?php
                                                foreach ($view->teams as $team){
                                                    ?>
                                                    <tr>
                                                        <td><?php echo $team->getTeamName() ?></td>
                                                        <td><?php echo $team->getIsBusy() ?></td>
                                                        <td>
                                                            <button type="button" class="btn btn-warning editTeamBtn" data-id="<?php echo $team->getTeamID() ?>" data-toggle="modal" data-target="#editTeamModal">
                                                                Edit
                                                            </button>
                                                        <td>
                                                            <button type="button" class="btn btn-danger deleteTeamBtn" data-id="<?php echo $team->getTeamID() ?>" data-toggle="modal" data-target="#deleteTeamWarning"<?php if ($team->getMemberCount() > 0) {echo "disabled";} ?> >
                                                                Delete
                                                            </button>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                ?>
                                            </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="pills-contact5" role="tabpanel" aria-labelledby="pills-contact-tab">

                                <div class="row" id="logSearch">
                                    <div class="col-md-12 mx-auto">
                                        <form action="adminPanel.php" method="POST">
                                            <div class="form-group">
                                                <label class="col-form-label" for="from">Date From</label>
                                                <input class="form-control" type="date"  name="from">
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label" for="to">Date To</label>
                                                <input class="form-control" type="date"  name="to">
                                            </div>

                                            <div>
                                                <input class="btn btn-primary" type="submit" value="Search Logs" name="logsSubmit">
                                            </div>
                                        </form>
                                    </div>
                                </div>

                                <div class="row" id="users">
                                    <div class="col-lg-12 text-center">
                                    <h1>Legend</h1>
                                </div>
                                <div class="col-md-12 mx-auto">
                                    <table class="table table-bordered align-content-center text-center">
                                        <tr>
                                            <th>Created</th>
                                            <th>Updated</th>
                                            <th>Generated</th>
                                            <th>Deleted</th>
                                        </tr>

                                        <tr>
                                            <td class="alert-success"></td>
                                            <td class="alert-warning"></td>
                                            <td class="alert-info"></td>
                                            <td class="alert-danger"></td>
                                        </tr>
                                    </table>
                                </div>
                                    <div class="col-md-12 mx-auto">
                                        <div class="card card-body bg-light mt-5">
                                            <h1 class="card-title">Logs</h1>
                                            <div class="table-overflow-y table-scroll" style="min-width: 750px;">

                                                <?php

                                                    foreach ($view->logs as $log){
                                                        $id = $log->getLogID();
                                                        $editor = $log->getLogEditor();
                                                        $action = $log->getLogAction();
                                                        $affUser = $log->getLogAffectedUser();
                                                        $affTeam = $log->getLogAffectedTeam();
                                                        $date = $log->getLogDate();
                                                        $alertType = "";
                                                        $icon = "";

                                                        switch ($action){
                                                            case "deleted":
                                                                $alertType = "danger";
                                                                $icon = "<i class=\"fas fa-minus\"></i>";
                                                                break;
                                                            case "created":
                                                                $alertType = "success";
                                                                $icon = "<i class=\"fas fa-plus\"></i>";
                                                                break;
                                                            case "updated":
                                                                $alertType = "warning";
                                                                $icon = "<i class=\"fas fa-pencil-alt\"></i>";
                                                                break;
                                                            case "generated a new rota":
                                                                $alertType = "info";
                                                                $affTeam = "";
                                                                $affUser = "";
                                                                $icon = "<i class=\"fas fa-calendar-plus\"></i>";
                                                                break;
                                                            case "published a new rota":
                                                                $alertType = "info";
                                                                $affTeam = "";
                                                                $affUser = "";
                                                                $icon = "<i class=\"fas fa-calendar-plus\"></i>";
                                                                break;
                                                            default:
                                                                $alertType = "secondary";
                                                        }

                                                        if ($affUser == "n/a"){ ?>
                                                            <div class="alert alert-<?php echo $alertType; ?>" role="alert">
                                                                <?php echo $icon . " Admin " . $editor . " " . $action . " " . $affTeam . " on " . $date . "!" ?>
                                                            </div>
                                                        <?php } elseif ($affTeam == "n/a"){ ?>
                                                            <div class="alert alert-<?php echo $alertType; ?>" role="alert">
                                                                <?php echo $icon . " Admin " . $editor . " " . $action . " " . $affUser . " on " . $date . "!" ?>
                                                            </div>
                                                        <?php } else { ?>
                                                            <div class="alert alert-info" role="alert">
                                                                <?php echo $icon . " Admin " . $editor . " " . $action . " on " . $date . "!" ?>
                                                            </div>
                                                        <?php }
                                                    }

                                                ?>

                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    <?php else : ?>
                        <h1>You do not have permission to view this page...</h1>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>



<?php require("templates/footer.phtml"); ?>