<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>

    <!-- TODO: Validation. -->
    // TODO: figure out a proper check for this?
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row" id="editUser">
            <div class="col-md-10 mx-auto">
                <div class="card card-body bg-light mt-5">
                    <h1 class="card-title">Edit User</h1>
                    <form action="editUser.php" method="post">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Edit your email</label>
                                <input type="email" class="form-control" id="inputEmail4">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Edit your password</label>
                                <input type="password" class="form-control" id="inputPassword4">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Edit your First Name</label>
                                <input type="password" class="form-control" id="inputPassword4">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Edit your Surname</label>
                                <input type="password" class="form-control" id="inputPassword4">
                            </div>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="isAdmin" id="isadmin">
                                <label class="form-check-label" for="isadmin">Admin?</label>
                            </div>
                            <button type="button" class="btn btn-success">Confirm</button>
                            <button type="button" class="btn btn-warning">Clear</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require("templates/footer.phtml"); ?>