<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>

    <!-- TODO: Validation. -->
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row" id="editUser">
            <div class="col-md-10 mx-auto">
                <div class="card card-body bg-light mt-5">
                    <h1 class="card-title">Edit User <?php echo $user->userID?></h1>
                    <form action="editUser.php" method="post">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Edit your First Name</label>
                                <input type="text" class="form-control" id="inputPassword4">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Edit your Surname</label>
                                <input type="text" class="form-control" id="inputPassword4">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Edit your email</label>
                                <input type="email" class="form-control" id="inputEmail4">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Edit your password</label>
                                <input type="password" class="form-control" id="inputPassword4">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Change Teams</label>
                                <div class="form-group">
                                    <select class="form-control" name="teamID">
                                        <?php
                                        foreach ($view->teams as $team) {
                                            ?>
                                            <option value="<?php echo $team->getTeamID() ?>">
                                                <?php echo $team->getTeamName() ?>
                                            </option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" name="isAdmin" id="isadmin">
                                    <label class="form-check-label" for="isadmin">Admin?</label>
                                </div>
                                <button type="button" name="submit" class="btn btn-success">Confirm</button>
                                <button type="button" class="btn btn-warning">Clear</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<?php require("templates/footer.phtml"); ?>