<?php require_once ("templates/header.phtml") ?>
<?php require_once ("templates/navbar.phtml") ?>

<?php
$rota = $view->rota;
?>
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Temporary Rota</h1>
                <a class="btn btn-danger" href="generateRota.php">Generate a new Rota</a>

            </div>
            <div class="col-lg-12">
                <a class="btn btn-primary" href="publishRota.php?to=<?php echo $rota->getTo() ?>&from=<?php echo $rota->getFrom() ?> &devA=<?php echo $rota->getDevA()->getUserID() ?>&devB=<?php echo $rota->getDevB()->getUserID() ?>">Publish this Rota</a>
            </div>

            <div class="col-lg-12">
                <div class="card card-body bg-light mt-5">
                    <h1 class="card-title">Rota</h1>

                    <table class="table">
                        <tr>
                            <th>From</th>
                            <th>To</th>
                            <th>Dev A</th>
                            <th>Dev B</th>
                        </tr>
                        <tr>
                            <th><?php echo $view->rota->getFrom() ?></th>
                            <th><?php echo $view->rota->getTo() ?></th>
                            <th><?php echo $view->rota->getDevA()->getUsername()?></th>
                            <th><?php echo $view->rota->getDevB()->getUsername()?></th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<?php require_once ("templates/footer.phtml") ?>
