<?php require_once ("templates/header.phtml") ?>
<?php require_once ("templates/navbar.phtml") ?>
<?php require("templates/editScheduleModal.phtml"); ?>

<div class="content-wrapper pt-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Temporary Rota</h1>
            </div>
            <form action="generateRota.php" method="POST">
                <div class="form-group">
                    <input class="form-control" type="date" name="from">
                    <input class="form-control" type="date" name="to">
                </div>

                <div class="form-group">
                    <input type="submit" name="submit" class="btn btn-danger" value="Generate a new Rota">
                </div>
            </form>
            <div class="col-lg-12">
                <form action="publishRota.php" method="POST">
                    <input type="hidden" name="schedules" value="<?php print base64_encode(serialize($view->schedules))?>">
                    <input type="submit" class="btn btn-primary" value="Publish Rotas">
                </form>
            </div>

            <div class="col-lg-12">
                <div class="card card-body bg-light mt-5">
                    <h1 class="card-title">Preview Schedules</h1>

                    <div class="table-scroll table-overflow-y">
                        <table class="table table-striped">
                            <tr>
                                <th>From</th>
                                <th>To</th>
                                <th>Dev A</th>
                                <th>Dev B</th>
                                <th>Edit Schedule</th>
                            </tr>
                            <?php
                            foreach ($view->schedules as $schedule) {
                                ?>
                                <tr>
                                    <th><?php echo $schedule->getFrom() ?></th>
                                    <th><?php echo $schedule->getTo() ?></th>
                                    <th><?php echo $schedule->getDevA()->getUsername()?></th>
                                    <th><?php echo $schedule->getDevB()->getUsername()?></th>
                                    <th>
                                        <button type="button" class="btn btn-warning editScheduleBtn" data-id="editScheduleModal" data-toggle="modal" data-target="#editScheduleModal">
                                            Edit
                                        </button>
                                    </th>
                                </tr>
                                <?php
                            }
                            ?>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<?php require_once ("templates/footer.phtml") ?>
