<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>

<?php
    if (isset($_SESSION['loggedIn'])) {
        echo "<h1>" .$_SESSION['username'] . "</h1>";
        echo "<a href='logout.php'>Logout</a>";
    } else {
        echo "<h1>Please Login :)</h1>";
    }
?>

    <div class="modal fade" id="loginModal" tabindex="-1" role="form">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalTitle">Login</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="login.php" method="post">
                        <div class="form-group">
                            <label for="username">Username: </label>
                            <input type="text" name="username" id="username" placeholder="Enter Username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Password: </label>
                            <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="rememberme">
                            <label class="form-check-label" for="rememberme">Remember Me</label>
                        </div>
                        <br>
                        <button type="submit" name="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Create User</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Create Team</a>
        </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">
                Login Modal
            </button>
        </div>
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">

            <form action="" method="post">
                <div class="form-row">
                    <div class="col">
                        <label for="teamname">First Name: </label>
                        <input type="text" name="firstname" id="firstname" class="form-control" placeholder="First name">
                    </div>
                    <div class="col">
                        <label for="teamname">Last Name: </label>
                        <input type="text" name="lastname" id="lastname" class="form-control" placeholder="Last name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="email">Email: </label>
                    <input type="text" name="email" id="email" class="form-control" placeholder="email">
                </div>
                <div class="form-group">
                    <label for="email">Team: </label>
                    <input type="text" name="team" id="team" class="form-control" placeholder="team">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="isadmin" id="isadmin">
                    <label class="form-check-label" for="isadmin">Admin?</label>
                </div>
                <br>
                <button type="submit" name="submit" class="btn btn-primary">Create</button>
            </form>

        </div>
        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">

            <form action="" method="post">
                <div class="form-group">
                    <label for="teamname">Team Name: </label>
                    <input type="text" name="teamname" id="teamname" placeholder="Enter a Team Name" class="form-control">
                </div>
                <br>
                <button type="submit" name="submit" class="btn btn-primary">Create</button>
            </form>

        </div>
    </div>

<?php require("templates/footer.phtml"); ?>