<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>

<?php
    if (isset($_SESSION['loggedIn'])) {
        echo "<h1>" .$_SESSION['username'] . "</h1>";
    } else {
        echo "<h1>Please Login :)</h1>";
    }
?>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">
        Login Modal
    </button>

    <div class="modal fade" id="loginModal" tabindex="-1" role="form">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalTitle">Login</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="login.php" method="post">
                        <div class="form-group">
                            <label for="username">Username: </label>
                            <input type="text" name="username" id="username" placeholder="Enter Username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Password: </label>
                            <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="rememberme">
                            <label class="form-check-label" for="rememberme">Remember Me</label>
                        </div>
                        <br>
                        <button type="submit" name="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

<?php require("templates/footer.phtml"); ?>