<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>
<?php require("templates/loginModal.phtml"); ?>
<?php require("templates/editUserModal.phtml"); ?>
<?php require("templates/editTeamModal.phtml"); ?>
<?php require("templates/deleteUserWarning.phtml"); ?>
<?php require("templates/deleteTeamWarning.phtml"); ?>

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Current Support Rota</h1>
                <table class="table">
                    <tr>
                        <th>Developer</th>
                        <th>From</th>
                        <th>To</th>
                    </tr>
                    <tr>
                        <?php
                        foreach ($view->rotas as $rota) {
                        ?>
                    <tr>
                        <td><?php echo $rota->getFrom() ?></td>
                        <td><?php echo $rota->getTo() ?></td>
                        <td><?php echo $rota->getDevA() ?></td>
                        <td><?php echo $rota->getDevB() ?></td>
                    </tr>
                    <?php
                    }
                    ?>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>



<?php require("templates/footer.phtml"); ?>