<?php require_once ("templates/header.phtml") ?>
<?php require_once ("templates/navbar.phtml") ?>

    <div class="row" id="users">
        <div class="col-md-12 mx-auto">
            <div class="card card-body bg-light mt-5">
                <h1 class="card-title">Logs</h1>
                <table>
                    <tr>
                        <th>
                            Log ID
                        </th>
                        <th>
                            Log ID
                        </th>
                        <th>
                            Log ID
                        </th>
                        <th>
                            Log ID
                        </th>
                    </tr>
                </table>
            </div>
        </div>
    </div>

<?php require("templates/footer.phtml"); ?>