<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>
<?php require("templates/loginModal.phtml"); ?>

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">Team</th>
                        <th scope="col">Name</th>
                        <?php for($i = 1; $i < 24; $i++){
                            echo "<th scope=\"col\">$i</th>";
                        } ?>
                    </tr>
                    </thead>
                    <tbody>
                        <?php for ($x = 0; $x < sizeof($view->teams); $x++){ ?>

                            <tr id="<?php echo $view->teams[$x]->getTeamID(); ?>">
                                <th scope="row"><?php echo $view->teams[$x]->getTeamName(); ?></th>
                                <td><?php echo $view->members[$x][0] ?></td>
                                <?php for($i = 1; $i < 24; $i++){
                                    echo "<th scope=\"col\"></th>";
                                } ?>
                            </tr>

                            <?php $isFirst = true;
                                for ($j = 0; $j < sizeof($view->members[$x]); $j++) {
                                    if ($isFirst){
                                        $isFirst = false;
                                        continue;
                                    } else {?>
                                        <tr>
                                        <th scope="row"></th>
                                        <td><?php echo $view->members[$x][$j] ?></td>
                                        <?php for($i = 1; $i < 24; $i++){
                                            echo "<th scope=\"col\"></th>";
                                        } ?>
                                        </tr>
                                <?php }} ?>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    const jsonThing = [
        {
            team: "Team 1",
            name: "Mark Otto",
            onSupport: [1,2,7,8]
        },
        {
            team: "Team 1",
            name: "Jacob Thornton",
            onSupport: [4,5,10,11]
        },
        {
            team: "Team 3",
            name: "Jane Doe",
            onSupport: [1,2,7,8]
        },
        {
            team: "Team 3",
            name: "Larry Doe",
            onSupport: [4,5,10,11]
        },
        // ACTUAL IN MEMORY STRUCTURE OF SCHEDULE OBJECT
        {
            from: "12-01-2020",
            to: "28-01-2020",
            devA: {
                id: 4,
                username: "devA@example.test",
                teamName: "fanatics Admin"
            },

            devB: {
                id: 9,
                username: "devB@example.test",
                teamName: "fanatics Production"
            }
        }
    ];

    /*const jsonFilterStuff = jsonThing.filter(x => x.from === "12-01-2020")
        .map(x => [x.devA.username, x.devB.username]);*/

    // const randomThing = document.querySelectorAll('table tbody tr');

    /*for (let i = 0; i < randomThing.length; i++){
        let randomThingName = randomThing[i].children[1].innerHTML;
        if (randomThingName === 'Larry Bird'){
            randomThing[i].children[8].setAttribute('class', 'bg-success');
        }
    }*/


</script>

<?php require("templates/footer.phtml"); ?>
