<?php require_once ("templates/header.phtml") ?>
<?php require_once ("templates/navbar.phtml") ?>

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Rota</h1>
                <a class="btn btn-primary" href="generateRota.php">Generate a new Rota</a>
            </div>
        </div>

        <div class="card card-body">
            <div class="card-header-pills">
                <div class="card-body">
                    <label for="datefrom">Date From:</label>
                    <input type="date" name="dateFrom" class="form-control" placeholder="<?php echo date("Y/m/d") ?>" id="from">
                    <label for="pwd">Date to:</label>
                    <input type="date" name="dateTo" class="form-control" placeholder="" id="to">
                </div>
            </div>
        </div>
        <a class="btn btn-primary" href="/rotaRange.php">Generate a new Rota</a>
        </form>
        </div>

                    <table class="table">
                        <tr>
                            <th>From</th>
                            <th>To</th>
                            <th>Dev A</th>
                            <th>Dev B</th>
                        </tr>
                        <?php
                            foreach ($view->rotas as $rota) {
                                ?>
                                <tr>
                                    <td><?php echo $rota->getFrom() ?></td>
                                    <td><?php echo $rota->getTo() ?></td>
                                    <td><?php echo $rota->getDevA() ?></td>
                                    <td><?php echo $rota->getDevB() ?></td>
                                </tr>
                                <?php
                            }
                        ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once ("templates/footer.phtml") ?>
