<?php require_once ("templates/header.phtml") ?>
<?php require_once ("templates/navbar.phtml") ?>

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Rota</h1>
            </div>
            <div class="col-lg-12">
                <a class="btn btn-primary-">Generate new Rota</a>
            </div>
        </div>
    </div>
</div>

<?php require_once ("templates/footer.phtml") ?>
