<?php require("templates/header.phtml"); ?>
<?php require("templates/navbar.phtml"); ?>
<?php require("templates/loginModal.phtml"); ?>

<?php
?>
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">Team</th>
                        <th scope="col">Name</th>
                        <?php for($i = 1; $i < 24; $i++){
                            echo "<th scope=\"col\">$i</th>";
                        } ?>
                    </tr>
                    </thead>
                    <tbody>
                        <?php for ($x = 0; $x < sizeof($view->teams); $x++){ ?>

                            <tr id="<?php echo $view->teams[$x]->getTeamID(); ?>">
                                <th scope="row"><?php echo $view->teams[$x]->getTeamName(); ?></th>
                                <td><?php echo $view->members[$x][0] ?></td>
                                <?php for($i = 1; $i < 24; $i++){
                                    echo "<th scope=\"col\"></th>";
                                } ?>
                            </tr>

                            <?php $isFirst = true;
                                for ($j = 0; $j < sizeof($view->members[$x]); $j++) {
                                    if ($isFirst){
                                        $isFirst = false;
                                        continue;
                                    } else {?>
                                        <tr>
                                        <th scope="row"></th>
                                        <td><?php echo $view->members[$x][$j] ?></td>
                                        <?php for($i = 1; $i < 24; $i++){
                                            echo "<th scope=\"col\"></th>";
                                        } ?>
                                        </tr>
                                <?php }} ?>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>

    let schedules = <?php echo json_encode($view->schedules);?>;
    console.log(schedules);

    let devNamesOnSched = schedules.filter(x => x._from === "February 10, 2020")
        .map(x => [x._devA, x._devB]);

    const [ devA, devB ] = devNamesOnSched[0];
    console.log(`${devA} and ${devB}`);

    let dateArray = [];

    schedules.forEach(x => dateArray.push(x._from));

    const scheduleTableHead = document.querySelectorAll('table thead th');

    console.log(scheduleTableHead[2]);

    // const randomThing = document.querySelectorAll('table tbody tr');

    /*for (let i = 0; i < randomThing.length; i++){
        let randomThingName = randomThing[i].children[1].innerHTML;
        if (randomThingName === 'Larry Bird'){
            randomThing[i].children[8].setAttribute('class', 'bg-success');
        }
    }*/


</script>

<?php require("templates/footer.phtml"); ?>
