<div class="modal fade" id="deleteUserWarning" tabindex="-1" role="form">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteUserWarningTitle">Delete User</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h6 class="f-opensans-bold">Are you sure you want to delete <span id="duw-name">Placeholder</span>?</h6>
                <p class="f-raleway-thin">This action is irreversible!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-danger" id="duw-button" href="#">Delete</a>
            </div>
        </div>
    </div>
</div>