<div class="modal fade" id="editTeamModal" tabindex="-1" role="form">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editTeamModalTitle">Edit User</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span id="edit-team-error"></span>
                <form method="post" id="edit-team-form">
                    <div class="form-group">
                        <label for="etm-teamname">Team Name: </label>
                        <input type="text" name="username" id="etm-teamname" placeholder="Enter a Team Name" class="form-control" required>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="etm-isbusy">
                        <label class="form-check-label" for="etm-isbusy">Is the team busy?</label>
                    </div>
                    <br>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="submit" class="btn btn-success">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.editTeamBtn').on('click', function () {
            const $tr = $(this).closest('tr');

            const data = $tr.children("td").map(function () {
                return $(this).text();
            }).get();

            $('#etm-teamname').val(data[0]);

            if (data[1] === "Yes"){
                $('#etm-isbusy').prop('checked',true);
            } else {
                $('#etm-isbusy').prop('checked',false);
            }
        });
    });
</script>