<div class="modal fade" id="editTeamModal" tabindex="-1" role="form">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editTeamModalTitle">Edit Schedule</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span id="edit-team-error"></span>
                <form method="post" id="edit-team-form">
                    <input type="hidden" name="teamID" id="etm-teamID">
                    <div class="form-group">
                        <label for="etm-teamname">Team Name: </label>
                        <input type="text" name="teamName" id="etm-teamname" placeholder="Enter a Team Name" class="form-control" required>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="etm-isbusy" name="isBusy">
                        <label class="form-check-label" for="etm-isbusy">Is the team busy?</label>
                        <div class="form-check">
                            <label class="form-check-label" for="eum-isBusy">Team is unavailable</label>

                            <input type="date" id="etm-isBusyFrom" name="isBusyFrom"  placeholder="Date From" class="form-control">

                            <input type="date" id="etm-isBusyTo" name="isBusyTo" placeholder="Date To" class="form-control">

                        </div>
                    </div>
                    <br>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="submit" class="btn btn-success">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>