<div class="modal fade" id="editUserModal" tabindex="-1" role="form">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editUserModalTitle">Edit User</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span id="edit-user-error"></span>
                <form method="post" id="edit-user-form">
                    <input type="hidden" name="userID" id="eum-userID">
                    <div class="form-group">
                        <label for="eum-username">Username: </label>
                        <input type="text" name="username" id="eum-username" placeholder="Enter Username" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="eum-firstName">First Name: </label>
                        <input type="text" name="firstName" id="eum-firstName" placeholder="John" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="eum-lastName">Last Name: </label>
                        <input type="text" name="lastName" id="eum-lastName" placeholder="Doe" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="eum-team">Team: </label>
                        <select class="form-control" name="teamID" id="eum-team" required>
                            <?php
                                foreach ($view->teams as $team) {
                                    ?>
                                    <option value="<?php echo $team->getTeamID() ?>"><?php echo $team->getTeamName() ?></option>
                                    <?php
                                }
                            ?>
                        </select>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="eum-isAbsent" name="isAbsent">
                        <label class="form-check-label" for="eum-isAbsent">User is Absent</label>

                        <input type="date" id="absentDateFrom" name="absentDateFrom"  placeholder="Date From" class="form-control">

                        <input type="date" id="absentDateTo" name="absentDateTo" placeholder="Date To" class="form-control">

                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="eum-isadmin" name="isAdmin">
                        <label class="form-check-label" for="eum-isadmin">User is an Admin?</label>
                    </div>
                    <br>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="submit" class="btn btn-success">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>