
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/loginAjax.js"></script>
    <?php if (isset($view->pageName) && $view->pageName == "admin") : ?>
        <script src="/assets/js/modalDataPassing.js"></script>
        <script src="/assets/js/otherAjax.js"></script>
    <?php endif; ?>
</body>
</html>