<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $view->title; ?></title>

        <!-- Meta Tags -->
        <meta charset="utf-8">
        <meta name="description" content="Rota System for Fanatics">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Style Sheets -->
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/css/main.css" rel="stylesheet">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Raleway:100,300,400&display=swap" rel="stylesheet">
    </head>
    <body>