<div class="modal fade" id="loginModal" tabindex="-1" role="form">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalTitle">Login</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span id="login-error"></span>
                <form method="post" id="login-form">
                    <div class="form-group">
                        <label for="username">Username: </label>
                        <input type="text" name="username" id="username" placeholder="Enter Username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Password: </label>
                        <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="rememberme">
                        <label class="form-check-label" for="rememberme">Remember Me</label>
                    </div>
                    <br>
                    <button type="submit" name="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>
