<!-- Top Navbar Start -->
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Logo Here</a>
    <ul class="navbar-nav px-3">
        <li class="navbar-item text-nowrap">
            <!-- TODO: Can probably just check if loggedIn is set -->
            <?php if (isset($_SESSION["loggedIn"]) && ($_SESSION["loggedIn"] == true)) : ?>
                <a class="nav-link n-text" href="logout.php">Logout</a>
            <?php else : ?>
                <a class="nav-link n-text" href="#" data-toggle="modal" data-target="#loginModal">Login</a>
            <?php endif; ?>
        </li>
    </ul>
</nav>
<!-- Top Navbar End -->

<!-- Sidebar Start -->
<div class="f-wrapper" id="wrapper">
    <div class="sidebar-wrapper">
        <ul class="sidebar-nav text-center">
            <li>
                <a href="rota.php" class="n-text"><i class="far fa-calendar-alt"></i> Rota</a>
            </li>
            <?php if (isset($_SESSION["loggedIn"]) && ($_SESSION["loggedIn"] == true)) : ?>
                <li>
                    <a href="#" class="n-text"><i class="fas fa-handshake"></i> Shift Swap</a>
                </li>
                <li>
                    <!-- TODO: Add verification check (if $_SESSION['isAdmin'] or something)-->
                    <a href="adminPanel.php" class="n-text"><i class="fas fa-shield-alt"></i> Admin Panel</a>
                </li>
                <li>
                    <a href="#" class="n-text"><i class="fas fa-cog"></i> Settings</a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
    <!-- Sidebar End -->

