<!-- Top Navbar Start -->
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Logo Here</a>
    <ul class="navbar-nav px-3">
        <li class="navbar-item text-nowrap">
            <a class="nav-link" href="#" class="n-text">Login</a>
        </li>
    </ul>
</nav>
<!-- Top Navbar End -->

<!-- Sidebar Start -->
<div class="f-wrapper" id="wrapper">
    <div class="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li>
                <a href="#" class="n-text">Schedule</a>
            </li>
            <li>
                <a href="#" class="n-text">Shift Swap</a>
            </li>
            <li>
                <a href="#" class="n-text">Admin Panel</a>
            </li>
            <li>
                <a href="#" class="n-text">Settings</a>
            </li>
        </ul>
    </div>
    <!-- Sidebar End -->

